### ISSUE TITLE
Header File

### ISSUE THREAD

**Issue by shoaibrayeen** [disha-surana/basic-programs#1]
Why do you use header files which are not used in this program? This might increase your runtime. You should remove such header files which would not be used in your program.

**Comment by disha-surana** [comment]
okay, i will keep this in mind in future.
But actually i have just coded the respective function asked in hacker-rank problems and copied the entire code here.

**Comment by shoaibrayeen** [comment]
I know that you are copying the code. In case  , if you need more informations regarding this  , then you can contact me and I would like to help you in such cases.
